export const TRAINING_CONTEXT = {
  trainSize: 3611,
  testSize: 903,
  testRatio: 20,
  seed: 88,
  validation: 'Stratified 5-Fold',
  target: '클래스 1: 비이탈 · 클래스 2: 이탈',
}

export const MODEL_EVALUATIONS = [
  {
    id: 'random-forest',
    category: 'machine-learning',
    name: 'Random Forest',
    type: '앙상블 · 배깅',
    description: '여러 결정 트리의 투표를 결합해 비선형 관계를 학습하는 모델',
    feature: '균형 가중치 적용 후 이탈 탐지 성능을 개선',
    selected: false,
    accuracy: 66,
    precision: 49,
    recall: 55,
    f1: 52,
    cvF1: 61.25,
    searchMethod: 'RandomizedSearchCV · F1-macro · 20회',
    hyperparameters: [
      ['n_estimators', '200'],
      ['max_depth', '10'],
      ['min_samples_split', '3'],
      ['min_samples_leaf', '1'],
      ['class_weight', 'balanced'],
    ],
    interpretation:
      '이탈 재현율은 55%로 기본 모델보다 개선됐지만, 전체 정확도는 66%로 낮아졌습니다.',
    confusionMatrix: {
      normalized: true,
      unit: 'percent',
      labels: ['비이탈', '이탈'],
      values: [[71.2, 28.8], [44.6, 55.4]],
    },
  },
  {
    id: 'logistic-regression',
    category: 'machine-learning',
    name: 'Logistic Regression',
    type: '선형 분류',
    description: '각 입력 변수의 선형 결합으로 이탈 확률을 추정하는 기준 모델',
    feature: '해석이 쉽고 균형 가중치로 이탈 클래스에 대응',
    selected: false,
    accuracy: 61,
    precision: 43,
    recall: 56,
    f1: 48,
    cvF1: 59.92,
    searchMethod: 'RandomizedSearchCV · F1-macro · 20회',
    hyperparameters: [
      ['solver', 'liblinear'],
      ['penalty', 'l2'],
      ['max_iter', '2000'],
      ['class_weight', 'balanced'],
      ['C', '0.02807'],
    ],
    interpretation:
      '이탈 재현율은 56%지만 정밀도와 정확도가 상대적으로 낮아 최종 모델로 선택하지 않았습니다.',
    confusionMatrix: {
      normalized: true,
      unit: 'percent',
      labels: ['비이탈', '이탈'],
      values: [[63.0, 37.0], [44.0, 56.0]],
    },
  },
  {
    id: 'gradient-boosting',
    category: 'machine-learning',
    name: 'Gradient Boosting',
    type: '앙상블 · 부스팅',
    description: '이전 트리의 오류를 다음 트리가 순차적으로 보완하는 모델',
    feature: '정확도는 높지만 이탈 클래스 누락이 많음',
    selected: false,
    accuracy: 69,
    precision: 59,
    recall: 18,
    f1: 28,
    cvF1: null,
    searchMethod: 'RandomizedSearchCV · F1-macro · 20회',
    hyperparameters: null,
    interpretation:
      '정확도는 69%로 가장 높지만 실제 이탈자의 18%만 탐지해 이탈 방지 목적에는 적합하지 않았습니다.',
    confusionMatrix: {
      normalized: true,
      unit: 'percent',
      labels: ['비이탈', '이탈'],
      values: [[93.9, 6.1], [81.9, 18.1]],
    },
  },
  {
    id: 'xgboost',
    category: 'machine-learning',
    name: 'XGBoost',
    type: '앙상블 · 부스팅',
    description: '정규화와 클래스 가중치를 활용하는 고성능 그래디언트 부스팅 모델',
    feature: '이탈 재현율과 F1의 균형을 기준으로 최종 선택',
    selected: true,
    accuracy: 62,
    precision: 45,
    recall: 64,
    f1: 53,
    cvF1: 60.23,
    threshold: 0.48,
    searchMethod: 'RandomizedSearchCV · F1-macro · 20회',
    hyperparameters: [
      ['n_estimators', '200'],
      ['learning_rate', '0.05'],
      ['max_depth', '2'],
      ['min_child_weight', '3'],
      ['subsample', '0.85'],
      ['scale_pos_weight', '2.0268'],
    ],
    interpretation:
      '정확도보다 이탈자 누락 방지를 우선했습니다. 비교 모델 중 가장 높은 이탈 재현율 64%와 F1 53%를 기록했습니다.',
    confusionMatrix: {
      normalized: true,
      unit: 'percent',
      labels: ['비이탈', '이탈'],
      values: [[61.2, 38.8], [35.9, 64.1]],
    },
  },
  {
    id: 'catboost',
    category: 'machine-learning',
    name: 'CatBoost',
    type: '앙상블 · 부스팅',
    description: '균형 가중치를 자동 적용하고 순차 부스팅으로 학습하는 모델',
    feature: '정밀도와 재현율이 비교적 고르게 나타남',
    selected: false,
    accuracy: 64,
    precision: 46,
    recall: 54,
    f1: 50,
    cvF1: null,
    searchMethod: 'RandomizedSearchCV · F1-macro · 20회',
    hyperparameters: null,
    interpretation:
      '이탈 F1은 50%로 균형적이지만 XGBoost보다 이탈 재현율과 F1이 낮았습니다.',
    confusionMatrix: {
      normalized: true,
      unit: 'percent',
      labels: ['비이탈', '이탈'],
      values: [[68.9, 31.1], [46.0, 54.0]],
    },
  },
  {
    id: 'mlp',
    name: 'MLP',
    category: 'deep-learning',
    type: '딥러닝 · 다층 퍼셉트론',
    description: '두 개의 은닉층으로 정형 데이터의 비선형 패턴을 학습하는 PyTorch 신경망',
    feature: '검증 Recall 68% 목표를 만족하는 임계값으로 이탈 탐지를 조정',
    selected: false,
    accuracy: 58.8,
    precision: 42.23,
    recall: 67.45,
    f1: 51.94,
    auc: 65.83,
    cvF1: null,
    threshold: 0.36,
    trainSize: 2708,
    validationSize: 903,
    testSize: 903,
    splitSeed: 42,
    searchMethod: '검증 Recall 68% 이상에서 정확도가 가장 높은 임계값 탐색',
    hyperparameters: [
      ['input_dim', '27'],
      ['hidden_dims', '32 → 16'],
      ['activation', 'ReLU'],
      ['dropout', '0.1'],
      ['batch_size', '64'],
      ['learning_rate', '0.0003'],
      ['weight_decay', '0.00001'],
      ['optimizer', 'Adam'],
      ['loss', 'BCEWithLogitsLoss'],
      ['pos_weight', '1.2564'],
    ],
    architecture: [
      { name: '입력층', units: '27 features' },
      { name: '은닉층 1', units: '32 · ReLU · Dropout' },
      { name: '은닉층 2', units: '16 · ReLU · Dropout' },
      { name: '출력층', units: '1 logit · Sigmoid' },
    ],
    trainingConfig: {
      maxEpochs: 10000,
      stoppedEpoch: 126,
      earlyStopping: 'validation loss · patience 100',
      classBalance: '양성 클래스 가중치 1.2564 (원 가중치의 25% 효과)',
      validationAccuracy: 58.91,
      validationRecall: 69.46,
      testLoss: 0.6892,
    },
    history: null,
    interpretation:
      '이탈 재현율은 67.45%로 높지만 정확도와 정밀도는 낮습니다. ML 모델과 테스트 크기는 같아도 분할 seed가 달라 동일 샘플에 대한 직접 비교는 아닙니다.',
    confusionMatrix: {
      normalized: true,
      unit: 'percent',
      labels: ['비이탈', '이탈'],
      values: [[54.5, 45.5], [32.6, 67.4]],
    },
  },
]

export function findModel(modelId) {
  return MODEL_EVALUATIONS.find((model) => model.id === modelId)
}
